#!/bin/sh
. "$(dirname $0)/_/husky.sh"

set -e

YELLOW='\033[0;33m'
NC='\033[0m'

exec </dev/tty
if ! yarn --silent changeset status; then
  echo "If wanted to push without creating a changeset use \`yarn changeset --empty\` before pushing."
  echo "${YELLOW}Creating changeset now...${NC}"
  yarn --silent changeset
  echo "${YELLOW}Please run \`git push\` again.${NC}"
  exit 1
fi
