#!/bin/sh
. "$(dirname $0)/_/husky.sh"

exec </dev/tty
if ! node ./scripts/is-changeset-present.js; then
  yarn changeset
  git push --no-verify
  echo "Running $(git push) again now that changeset is present."
  git push $3 $2
fi
